Vidly/Vidly/Controllers/RentalsController.cs
using System.Web.Mvc;

namespace Vidly.Controllers
{
    public class RentalsController : Controller
    {
        public ActionResult New()
        {
            return View();
        }
    }
}

Vidly/Vidly/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    @Html.Partial("_NavBar")
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Vidly - Hayder Yahya</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/lib")
    @RenderSection("scripts", required: false)
</body>
</html>

Vidly/Vidly/Views/Shared/_NavBar.cshtml
<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            @Html.ActionLink(Vidly.Recources.HomeTexts.Vidly, "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li>@Html.ActionLink(Vidly.Recources.HomeTexts.NewRental, "New", "Rentals")</li>
                <li>@Html.ActionLink(Vidly.Recources.HomeTexts.Costumers, "Index", "Customers")</li>
                <li>@Html.ActionLink(Vidly.Recources.HomeTexts.Movies, "Index", "Movies")</li>
                <li>@Html.ActionLink(Vidly.Recources.HomeTexts.Language, "Index", "Language")</li>
            </ul>
            @Html.Partial("_LoginPartial")
        </div>
    </div>
</div>